version: '3.8'

services:
  # React Frontend Development Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: video_sonification-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true # Enables hot-reloading in Docker
    command: yarn dev --host 0.0.0.0 --base=/video_sonification/
    networks:
      - video_sonification-network

  # Python Implementation of DataService
  python-service:
    build:
      context: ./microservices/python_service
      dockerfile: Dockerfile
    container_name: video_sonification-python-service
    volumes:
      - ./microservices/python_service:/app
    ports:
      - "5000:5000"
    networks:
      - video_sonification-network
    environment:
      - SERVICE_NAME=python-data-service
      - SERVICE_PORT=5000

  # Go Implementation of DataService
  go-service:
    build:
      context: ./microservices/go_service
      dockerfile: Dockerfile
    container_name: video_sonification-go-service
    volumes:
      - ./microservices/go_service:/app
    ports:
      - "5001:5001"
    networks:
      - video_sonification-network
    environment:
      - SERVICE_NAME=go-data-service
      - SERVICE_PORT=5001

  # Multi-Band Motion Analysis Service with GPU Support
  multi-band-analysis:
    build:
      context: ./microservices/multi_band_analysis
      dockerfile: Dockerfile
    container_name: video_sonification-multi-band-analysis
    volumes:
      - ./microservices/multi_band_analysis:/app
    ports:
      - "5002:5000"
    networks:
      - video_sonification-network
    environment:
      - SERVICE_NAME=multi-band-analysis
      - SERVICE_PORT=5000
      - NATS_URL=nats://nats:4222
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

  # NATS Message Broker
  nats:
    image: nats:latest
    container_name: video_sonification-nats
    ports:
      - "4222:4222" # Client connections
      - "8222:8222" # HTTP monitoring
    networks:
      - video_sonification-network
    command: "--jetstream"

volumes:
  node_modules:


networks:
  video_sonification-network:
    driver: bridge
